import sqlite3
import os
import requests
import streamlit as st
import ollama
import re 

class AiAgent:
    # base class for AI Agent to ask questions
    def ask_questions (self , question):
        raise NotImplementedError("This method should be implemented by subclasses")
    

  
    # method to provide schema context to the agent
    # this is where we will set the rules and the schema information for the agent to generate SQL queries
    # take this like a rulebook for the agent to follow when generating SQL queries
    def get_schema_context(self) -> str:
        return """
            Table: traffic_data

            Columns:
            - id (INTEGER, primary key)
            - timestamp (TEXT)
            - pin_12 (INTEGER): Red light (1 = ON, 0 = OFF)
            - pin_7 (INTEGER): Yellow light (1 = ON, 0 = OFF)
            - pin_8 (INTEGER): Green light (1 = ON, 0 = OFF)

            Rules:
            - Generate ONLY a valid SQLite query.
            - Do NOT use markdown code blocks.
            - Do NOT add explanations or extra text.
            - Use only the table and columns listed above.
            - Use pin_12 = 1 for red light counts.
            - Use pin_7 = 1 for yellow light counts.
            - Use pin_8 = 1 for green light counts.
            - Use COUNT(*) for total records.
            - Use ORDER BY timestamp DESC LIMIT 1 for the latest record.
            - Output SQL only.
            """
    

    # method to clean the SQL query generated by the agent
    # this is where the function will clean the SQL query generated by the agent to 
    # ensure it is in a valid format for execution against the SQLite database
    def clean_sql(self , sql_string: str) -> str:

        if not sql_string or not isinstance(sql_string, str):
            return ""

        # strip the string of leading and trailing whitespace
        sql = sql_string.strip()
        
        # use regex to extract the SQL query if it's wrapped in markdown code blocks
        match = re.search(r"```(?:sql|sqlite)?\s*(.*?)```", sql, re.IGNORECASE)
        
        # if a match is found, extract the SQL query from the code block
        if match:
            sql = match.group(0)

 
        else:
            # if no code block is found
            # just remove any leading keywords that might be present and 
            # return the cleaned SQL string
            sql = re.sub(r'^(```[a-zA-Z]*|ite|sql|sqlite)\s*', '', sql, flags=re.IGNORECASE)
            sql = sql.replace('```', '').strip()

        # remove code block markers if present
        # gemma3 generates code blocks with ```sql ... ``` format, so we need to clean that up
        
        if sql.startswith("```"):
            sql = sql.replace("```sql", "").replace("```", "").strip()

        return sql
    

    
    

    
    
