import sqlite3
import os
import requests
import streamlit as st
import ollama

class AiAgent:
    # base class for AI Agent to ask questions
    def ask_questions (self , question):
        raise NotImplementedError("This method should be implemented by subclasses")
    

  
    # method to provide schema context to the agent
    def get_schema_context(self) -> str:

        # parse the schema from the database table and return it as a string
        return """
        
        Table : traffic_data 

        Columns:
        - timestamp (TEXT, format: YYYY-MM-DD HH:MM:SS)
        - pin_12 (INTEGER, values: 0 or 1)
        - pin_7 (INTEGER, values: 0 or 1)
        - pin_8 (INTEGER, values: 0 or 1)

        """
    

    # method to clean the SQL query generated by the agent
    def clean_sql(self , sql_string: str) -> str:

        sql = sql_string.strip().rstrip(';')

        # remove code block markers if present
        # gemma3 generates code blocks with ```sql ... ``` format, so we need to clean that up
        
        if sql.startswith("```"):
            sql = sql.replace("```sql", "").replace("```", "").strip()

        return sql
    
