from urllib import response
from .base_factory import AiAgent
import ollama
import sqlite3
import os
import requests

class OllamaFactory(AiAgent):

    # method to get the model name from environment variable or use default
    # init function is used to initialize the Ollama client and set the model name based on 
    # environment variable or default value
    def __init__(self, model_name: str = "gemma3:1b" , host: str = "http://localhost:11434"):

        # set the model name from the env variable or use the default value
        self.model_name = model_name

        # connect to ollama server using specified host and init the client
        self.client = ollama.Client(host=host)
        
    # method to get the database schema context as a string
    def ask_questions(self , question:str) -> tuple[list , list] | str:

        system_instructions = f"""
          
           You are an SQL expert and data analyst. You have access to a database with the following schema:
              {self.get_schema_context()}

            Given a user's natural language question, look at the schema and return ONLY the valid SQLite query. 
            Do not include any introductory text, markdown formatting, or backticks (e.g., do NOT wrap it in ```sql). 
            Just return the raw query string.
        """


        try :

            # parse the required parameters 
            # send requests to ollama server to generate sql query
            response = self.client.generate(self.model_name,
                                       system=system_instructions,
                                       prompt = question,
                                       options={"temperature": 0.4, "max_tokens": 500}
                                       )
            
            # get the raw sql query generated by ollama model
            raw_sql = response.get("response" , "")

            # print for debugging purposes 
            print("Ollama connection test response:" , response)  

            # clean the generated raw sql query to remove any unwanted characters or formatting
            generated_sql = self.clean_sql(raw_sql)

            # for debugging purposes , print the generated SQL query to command line
            print("Generated SQL Query:", generated_sql)

            # execute the generated sql query against the SQLite database and fetch the results
            conn = sqlite3.connect('traffic_data.db')
            cursor = conn.cursor()
            cursor.execute(generated_sql)
            results = cursor.fetchall()

            # return the results along with the column names for better readability and usability in the frontend
            columns = [description[0] for description in cursor.description]
            conn.close()

            return results , columns

            
        
        except Exception as e:
            return f"Error generating SQL query: {e}"
        


    
        

    
                                       
    
    

